### ISSUE TITLE
errors when compiling the mod

### ISSUE THREAD

**Issue by PHGaming121** [Huier-Huang/TownOfHostEdited-Update#1]
i cant compile the TOHE project because it shows some errors
it says cant found package:
Samboy063.LIbCpp2IL
StableNameDotNet
Disarm

im using this repo:https://github.com/Loonie-Toons/TOHE-Restored
can u guys help?

**Comment by PHGaming121** [comment]
asking here because the TOHE restored doesnt have how to create issues

**Comment by Huier-Huang** [comment]
Add the Cpp2IL nuget source to visual Studio, the nuget source is located at https://github.com/SamboyCoding/Cpp2IL/releases/tag/2022.1.0-preview1里面有说明

**Comment by Huier-Huang** [comment]
Add the nuget source for Cpp2IL in visual Studio, the nuget source address is described at https://github.com/SamboyCoding/Cpp2IL/releases/tag/2022.1.0-preview1
